[package]
name = "rilibot"
version = "3.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
lazy_static = "1.5.0"
rand = "0.9.2"
serenity = "0.12.4"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "full"] }
tokio-postgres = "0.7.13"
