[package]
name = "rilibot"
version = "3.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
lazy_static = "1.5.0"
serenity = "0.12.4"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread", "full"] }
tokio-postgres = "0.7.13"
